name: Github actions - Push Basic Example 2
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
    - release-1
    - main
    #branches-ignore:
    #- main
    paths:
      - '**.txt'
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: echo "PUSH - Comments of workflow"