name: Github actions - Push Basic Example
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: echo "Pull Request test 1 - Comments of workflow".
        # end